export const REQUEST_CATEGORIES_DATA = 'REQUEST_CATEGORIES_DATA';
export const REQUEST_POSTS_DATA = 'REQUEST_POSTS_DATA';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
