export const REQUEST_DATA = 'REQUEST_DATA';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
